version: '2'
services: 
    ropsten:
        image: ethereum/client-go:v1.10.1
        container_name: ropsten
        volumes:
            - /root/.ethereum/:/root/.ethereum
        command: --syncmode light --ropsten --nousb --http.api admin,personal,txpool,eth,web3 --http --http.addr 0.0.0.0 --cache=12288 --maxpeers=200
        ports:
            - 30303:30303
            - 30304:30304
            - 8546:8545
        restart: always

    rinkeby:
        image: ethereum/client-go:v1.10.1
        container_name: rinkeby
        volumes:
            - /root/.ethereum/:/root/.ethereum
        command: --syncmode light --rinkeby --nousb --http.api admin,personal,txpool,eth,web3 --http --http.addr 0.0.0.0 --cache=12288 --maxpeers=200
        ports:
            - 30303:30303
            - 30304:30304
            - 8546:8545
        restart: always

    mainet:
        image: ethereum/client-go:v1.10.1
        container_name: mainet
        volumes:
            - /root/.ethereum/:/root/.ethereum
        command: --syncmode light --nousb --http.api admin,personal,txpool,eth,web3 --http --http.addr 0.0.0.0 --cache=12288 --maxpeers=200
        ports:
            - 30303:30303
            - 30304:30304
            - 8546:8545
        restart: always        




        
