version: '2'
services: 
    psql:
        restart: always
        ports:
            - "5432:5432"
        image: postgres:13.2
        container_name: psql
        volumes:
            - /opt/psql-data/data:/var/lib/postgresql/data
            - /opt/psql-data/log:/var/log/postgresql
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres

